<?php
// This file generated by Propel 1.6.8 convert-conf target
return array (
  'Propel\\Rights' => 'uplink/Rights.php',
  'Propel\\RightsPeer' => 'uplink/RightsPeer.php',
  'Propel\\RightsQuery' => 'uplink/RightsQuery.php',
  'Propel\\User' => 'uplink/User.php',
  'Propel\\UserPeer' => 'uplink/UserPeer.php',
  'Propel\\UserQuery' => 'uplink/UserQuery.php',
  'Propel\\map\\RightsTableMap' => 'uplink/map/RightsTableMap.php',
  'Propel\\map\\UserTableMap' => 'uplink/map/UserTableMap.php',
  'Propel\\om\\BaseRights' => 'uplink/om/BaseRights.php',
  'Propel\\om\\BaseRightsPeer' => 'uplink/om/BaseRightsPeer.php',
  'Propel\\om\\BaseRightsQuery' => 'uplink/om/BaseRightsQuery.php',
  'Propel\\om\\BaseUser' => 'uplink/om/BaseUser.php',
  'Propel\\om\\BaseUserPeer' => 'uplink/om/BaseUserPeer.php',
  'Propel\\om\\BaseUserQuery' => 'uplink/om/BaseUserQuery.php',
);