<?php
// This file generated by Propel 1.6.8 convert-conf target
// from XML runtime conf file D:\xampp\htdocs\uplink\module\Propel\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'uplink_test' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=uplink_test',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'uplink_test',
  ),
  'generator_version' => '1.6.8',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-uplink-conf.php');
return $conf;